// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: jobs.proto

package jobs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type JobGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,5,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGroup) Reset() {
	*x = JobGroup{}
	mi := &file_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGroup) ProtoMessage() {}

func (x *JobGroup) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGroup.ProtoReflect.Descriptor instead.
func (*JobGroup) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *JobGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobGroup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobGroup) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobGroup) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobGroup) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type GetJobGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobGroupRequest) Reset() {
	*x = GetJobGroupRequest{}
	mi := &file_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobGroupRequest) ProtoMessage() {}

func (x *GetJobGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobGroupRequest.ProtoReflect.Descriptor instead.
func (*GetJobGroupRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobGroup      *JobGroup              `protobuf:"bytes,1,opt,name=job_group,json=jobGroup,proto3" json:"job_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobGroupResponse) Reset() {
	*x = GetJobGroupResponse{}
	mi := &file_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobGroupResponse) ProtoMessage() {}

func (x *GetJobGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobGroupResponse.ProtoReflect.Descriptor instead.
func (*GetJobGroupResponse) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobGroupResponse) GetJobGroup() *JobGroup {
	if x != nil {
		return x.JobGroup
	}
	return nil
}

var File_jobs_proto protoreflect.FileDescriptor

const file_jobs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jobs.proto\x12\x15krypton.v1.admin.jobs\"f\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x9b\x01\n" +
	"\bJobGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12.\n" +
	"\x04jobs\x18\x05 \x03(\v2\x1a.krypton.v1.admin.jobs.JobR\x04jobs\"$\n" +
	"\x12GetJobGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x13GetJobGroupResponse\x12<\n" +
	"\tjob_group\x18\x01 \x01(\v2\x1f.krypton.v1.admin.jobs.JobGroupR\bjobGroup2r\n" +
	"\n" +
	"JobService\x12d\n" +
	"\vGetJobGroup\x12).krypton.v1.admin.jobs.GetJobGroupRequest\x1a*.krypton.v1.admin.jobs.GetJobGroupResponseB8Z6github.com/openkcm/krypton/pkg/api/v1/proto/admin/jobsb\x06proto3"

var (
	file_jobs_proto_rawDescOnce sync.Once
	file_jobs_proto_rawDescData []byte
)

func file_jobs_proto_rawDescGZIP() []byte {
	file_jobs_proto_rawDescOnce.Do(func() {
		file_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)))
	})
	return file_jobs_proto_rawDescData
}

var file_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jobs_proto_goTypes = []any{
	(*Job)(nil),                 // 0: krypton.v1.admin.jobs.Job
	(*JobGroup)(nil),            // 1: krypton.v1.admin.jobs.JobGroup
	(*GetJobGroupRequest)(nil),  // 2: krypton.v1.admin.jobs.GetJobGroupRequest
	(*GetJobGroupResponse)(nil), // 3: krypton.v1.admin.jobs.GetJobGroupResponse
}
var file_jobs_proto_depIdxs = []int32{
	0, // 0: krypton.v1.admin.jobs.JobGroup.jobs:type_name -> krypton.v1.admin.jobs.Job
	1, // 1: krypton.v1.admin.jobs.GetJobGroupResponse.job_group:type_name -> krypton.v1.admin.jobs.JobGroup
	2, // 2: krypton.v1.admin.jobs.JobService.GetJobGroup:input_type -> krypton.v1.admin.jobs.GetJobGroupRequest
	3, // 3: krypton.v1.admin.jobs.JobService.GetJobGroup:output_type -> krypton.v1.admin.jobs.GetJobGroupResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jobs_proto_init() }
func file_jobs_proto_init() {
	if File_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobs_proto_goTypes,
		DependencyIndexes: file_jobs_proto_depIdxs,
		MessageInfos:      file_jobs_proto_msgTypes,
	}.Build()
	File_jobs_proto = out.File
	file_jobs_proto_goTypes = nil
	file_jobs_proto_depIdxs = nil
}
