application:
  name: krypton
  environment: development

status:
  enabled: true
  address: ":8888"
  profiling: true

reconciler:
  maxReconcileCount: 10
  targets:
    - name: agent-aws
      address: localhost:9091

kmip:
  tcp:
    enabled: true
    address: ":5696"
  http:
    enabled: true
    address: ":8080"
    operation:
      only: [ 0x1, 0x2, 0x3 ]
