version: 3

env:
  GOEXPERIMENT: runtimesecret

includes:
  shared:
    taskfile: hack/common/Taskfile_service.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      LINTER_VERSION: v2.13.1
      CODE_DIRS: "{{.ROOT_DIR}}/api-specs/... {{.ROOT_DIR}}/cli/... {{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/internal/..."
      COMPONENTS: 'agent root'
      CHART_COMPONENTS: 'root'
      SKIP_VALIDATION_TESTS: 'true'

      IMG_COMPONENTS: 'agent root'
