// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: keys.proto

package keys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	KeyId          string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ParentId       string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	LifecycleState string                 `protobuf:"bytes,6,opt,name=lifecycle_state,json=lifecycleState,proto3" json:"lifecycle_state,omitempty"`
	ManagedBy      string                 `protobuf:"bytes,7,opt,name=managed_by,json=managedBy,proto3" json:"managed_by,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertKeyRequest) Reset() {
	*x = UpsertKeyRequest{}
	mi := &file_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertKeyRequest) ProtoMessage() {}

func (x *UpsertKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertKeyRequest.ProtoReflect.Descriptor instead.
func (*UpsertKeyRequest) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpsertKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UpsertKeyRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpsertKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertKeyRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpsertKeyRequest) GetLifecycleState() string {
	if x != nil {
		return x.LifecycleState
	}
	return ""
}

func (x *UpsertKeyRequest) GetManagedBy() string {
	if x != nil {
		return x.ManagedBy
	}
	return ""
}

func (x *UpsertKeyRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpsertKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertKeyResponse) Reset() {
	*x = UpsertKeyResponse{}
	mi := &file_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertKeyResponse) ProtoMessage() {}

func (x *UpsertKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertKeyResponse.ProtoReflect.Descriptor instead.
func (*UpsertKeyResponse) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{1}
}

type ActivateKeyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	KeyId    string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// parent_key_version is the parent's key version this key links to,
	// computed by root and persisted by the agent as-is. Unset for keys
	// whose parent linkage is not applicable.
	ParentKeyVersion *int32 `protobuf:"varint,3,opt,name=parent_key_version,json=parentKeyVersion,proto3,oneof" json:"parent_key_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivateKeyRequest) Reset() {
	*x = ActivateKeyRequest{}
	mi := &file_keys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateKeyRequest) ProtoMessage() {}

func (x *ActivateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateKeyRequest.ProtoReflect.Descriptor instead.
func (*ActivateKeyRequest) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ActivateKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ActivateKeyRequest) GetParentKeyVersion() int32 {
	if x != nil && x.ParentKeyVersion != nil {
		return *x.ParentKeyVersion
	}
	return 0
}

type ActivateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateKeyResponse) Reset() {
	*x = ActivateKeyResponse{}
	mi := &file_keys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateKeyResponse) ProtoMessage() {}

func (x *ActivateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateKeyResponse.ProtoReflect.Descriptor instead.
func (*ActivateKeyResponse) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{3}
}

var File_keys_proto protoreflect.FileDescriptor

const file_keys_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"keys.proto\x12\x16krypton.v1.agents.keys\"\xdc\x02\n" +
	"\x10UpsertKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12'\n" +
	"\x0flifecycle_state\x18\x06 \x01(\tR\x0elifecycleState\x12\x1d\n" +
	"\n" +
	"managed_by\x18\a \x01(\tR\tmanagedBy\x12L\n" +
	"\x06labels\x18\b \x03(\v24.krypton.v1.agents.keys.UpsertKeyRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11UpsertKeyResponse\"\x92\x01\n" +
	"\x12ActivateKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x121\n" +
	"\x12parent_key_version\x18\x03 \x01(\x05H\x00R\x10parentKeyVersion\x88\x01\x01B\x15\n" +
	"\x13_parent_key_version\"\x15\n" +
	"\x13ActivateKeyResponse2\xda\x01\n" +
	"\n" +
	"KeyService\x12b\n" +
	"\tUpsertKey\x12(.krypton.v1.agents.keys.UpsertKeyRequest\x1a).krypton.v1.agents.keys.UpsertKeyResponse\"\x00\x12h\n" +
	"\vActivateKey\x12*.krypton.v1.agents.keys.ActivateKeyRequest\x1a+.krypton.v1.agents.keys.ActivateKeyResponse\"\x00B9Z7github.com/openkcm/krypton/pkg/api/v1/proto/agents/keysb\x06proto3"

var (
	file_keys_proto_rawDescOnce sync.Once
	file_keys_proto_rawDescData []byte
)

func file_keys_proto_rawDescGZIP() []byte {
	file_keys_proto_rawDescOnce.Do(func() {
		file_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)))
	})
	return file_keys_proto_rawDescData
}

var file_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_keys_proto_goTypes = []any{
	(*UpsertKeyRequest)(nil),    // 0: krypton.v1.agents.keys.UpsertKeyRequest
	(*UpsertKeyResponse)(nil),   // 1: krypton.v1.agents.keys.UpsertKeyResponse
	(*ActivateKeyRequest)(nil),  // 2: krypton.v1.agents.keys.ActivateKeyRequest
	(*ActivateKeyResponse)(nil), // 3: krypton.v1.agents.keys.ActivateKeyResponse
	nil,                         // 4: krypton.v1.agents.keys.UpsertKeyRequest.LabelsEntry
}
var file_keys_proto_depIdxs = []int32{
	4, // 0: krypton.v1.agents.keys.UpsertKeyRequest.labels:type_name -> krypton.v1.agents.keys.UpsertKeyRequest.LabelsEntry
	0, // 1: krypton.v1.agents.keys.KeyService.UpsertKey:input_type -> krypton.v1.agents.keys.UpsertKeyRequest
	2, // 2: krypton.v1.agents.keys.KeyService.ActivateKey:input_type -> krypton.v1.agents.keys.ActivateKeyRequest
	1, // 3: krypton.v1.agents.keys.KeyService.UpsertKey:output_type -> krypton.v1.agents.keys.UpsertKeyResponse
	3, // 4: krypton.v1.agents.keys.KeyService.ActivateKey:output_type -> krypton.v1.agents.keys.ActivateKeyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keys_proto_init() }
func file_keys_proto_init() {
	if File_keys_proto != nil {
		return
	}
	file_keys_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keys_proto_goTypes,
		DependencyIndexes: file_keys_proto_depIdxs,
		MessageInfos:      file_keys_proto_msgTypes,
	}.Build()
	File_keys_proto = out.File
	file_keys_proto_goTypes = nil
	file_keys_proto_depIdxs = nil
}
