syntax = "proto3";


package krypton.v1.admin.keys;

option go_package = "github.com/openkcm/krypton/pkg/api/v1/proto/admin/keys";

service KeyService {
  rpc AnnounceKey(AnnounceKeyRequest) returns (AnnounceKeyResponse);
  rpc GetKey(GetKeyRequest) returns (GetKeyResponse);
  rpc GetParentKeys(GetParentKeysRequest) returns (GetParentKeysResponse);
  rpc GetDescendantKeys(GetDescendantKeysRequest) returns (GetDescendantKeysResponse);
  rpc ListKeys(ListKeysRequest) returns (ListKeysResponse);
}

message Key {
  string id = 1;
  string name = 2;
  string tenant_id = 3;
  string kind = 4;
  string parent_id = 5;
  string managed_by = 6;
  map<string, string> labels = 7;
  string life_cycle_state = 8;
  int64 created_at = 9;
  int64 updated_at = 10;
  KeyProcessingState key_processing_state = 11;
}

message KeyProcessingState {
  string status = 1;
  string job_id = 2;
}

message AnnounceKeyRequest {
  string tenant_id = 1;
  string kind = 2;
  string name = 3;
  string parent_id = 4;
  string target_name = 5;
  map<string, string> labels = 6;
}

message AnnounceKeyResponse {
  Key key = 1;
}

message GetKeyRequest {
  string id = 1;
  string tenant_id = 2;
}

message GetKeyResponse {
  Key key = 1;
}

message GetParentKeysRequest {
  string id = 1;
  string tenant_id = 2;
}

message GetParentKeysResponse {
  repeated Key keys = 1;
}

message GetDescendantKeysRequest {
  string id = 1;
  string tenant_id = 2;
}

message KeyTree {
  repeated Key keys = 1;
}

message GetDescendantKeysResponse {
  repeated KeyTree key_tree = 1;
}

message ListKeysRequest {
  string tenant_id = 1;
  string name = 2;
  string kind = 3;
  string life_cycle_state = 4;
  string managed_by = 5;
  map<string, string> labels = 6;
  bool is_order_by_created_at_asc = 7;
  string cursor = 8;
  int32 limit = 9;
}

message ListKeysResponse {
  repeated Key keys = 1;
  string cursor = 2;
}
