apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krypton.fullname" . }}-config
  namespace: {{ include "krypton.namespace" . }}
  labels:
    {{- include "krypton.labels" . | nindent 4 }}
immutable: {{ .Values.config.isImmutable | default false }}
data:
  config.yaml: |-
    {{- $cfg := omit .Values.config "isImmutable" }}
    {{- toYaml $cfg | nindent 4 }}
