// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: key.proto

package admin

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId           string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Kind               string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	ParentId           string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ManagedBy          string                 `protobuf:"bytes,6,opt,name=managed_by,json=managedBy,proto3" json:"managed_by,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LifeCycleState     string                 `protobuf:"bytes,8,opt,name=life_cycle_state,json=lifeCycleState,proto3" json:"life_cycle_state,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	KeyProcessingState *KeyProcessingState    `protobuf:"bytes,11,opt,name=key_processing_state,json=keyProcessingState,proto3" json:"key_processing_state,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Key) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Key) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Key) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Key) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Key) GetManagedBy() string {
	if x != nil {
		return x.ManagedBy
	}
	return ""
}

func (x *Key) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Key) GetLifeCycleState() string {
	if x != nil {
		return x.LifeCycleState
	}
	return ""
}

func (x *Key) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Key) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Key) GetKeyProcessingState() *KeyProcessingState {
	if x != nil {
		return x.KeyProcessingState
	}
	return nil
}

type KeyProcessingState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyProcessingState) Reset() {
	*x = KeyProcessingState{}
	mi := &file_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyProcessingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyProcessingState) ProtoMessage() {}

func (x *KeyProcessingState) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyProcessingState.ProtoReflect.Descriptor instead.
func (*KeyProcessingState) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{1}
}

func (x *KeyProcessingState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KeyProcessingState) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type AnnounceKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	TargetName    string                 `protobuf:"bytes,5,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceKeyRequest) Reset() {
	*x = AnnounceKeyRequest{}
	mi := &file_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceKeyRequest) ProtoMessage() {}

func (x *AnnounceKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceKeyRequest.ProtoReflect.Descriptor instead.
func (*AnnounceKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{2}
}

func (x *AnnounceKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AnnounceKeyRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AnnounceKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnnounceKeyRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *AnnounceKeyRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *AnnounceKeyRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type AnnounceKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceKeyResponse) Reset() {
	*x = AnnounceKeyResponse{}
	mi := &file_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceKeyResponse) ProtoMessage() {}

func (x *AnnounceKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceKeyResponse.ProtoReflect.Descriptor instead.
func (*AnnounceKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{3}
}

func (x *AnnounceKeyResponse) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{4}
}

func (x *GetKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{5}
}

func (x *GetKeyResponse) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetParentKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentKeysRequest) Reset() {
	*x = GetParentKeysRequest{}
	mi := &file_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentKeysRequest) ProtoMessage() {}

func (x *GetParentKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentKeysRequest.ProtoReflect.Descriptor instead.
func (*GetParentKeysRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{6}
}

func (x *GetParentKeysRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetParentKeysRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetParentKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Key                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentKeysResponse) Reset() {
	*x = GetParentKeysResponse{}
	mi := &file_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentKeysResponse) ProtoMessage() {}

func (x *GetParentKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentKeysResponse.ProtoReflect.Descriptor instead.
func (*GetParentKeysResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{7}
}

func (x *GetParentKeysResponse) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetDescendantKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDescendantKeysRequest) Reset() {
	*x = GetDescendantKeysRequest{}
	mi := &file_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDescendantKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescendantKeysRequest) ProtoMessage() {}

func (x *GetDescendantKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescendantKeysRequest.ProtoReflect.Descriptor instead.
func (*GetDescendantKeysRequest) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{8}
}

func (x *GetDescendantKeysRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDescendantKeysRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type KeyTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Key                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyTree) Reset() {
	*x = KeyTree{}
	mi := &file_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyTree) ProtoMessage() {}

func (x *KeyTree) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyTree.ProtoReflect.Descriptor instead.
func (*KeyTree) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{9}
}

func (x *KeyTree) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetDescendantKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyTree       []*KeyTree             `protobuf:"bytes,1,rep,name=key_tree,json=keyTree,proto3" json:"key_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDescendantKeysResponse) Reset() {
	*x = GetDescendantKeysResponse{}
	mi := &file_key_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDescendantKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescendantKeysResponse) ProtoMessage() {}

func (x *GetDescendantKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescendantKeysResponse.ProtoReflect.Descriptor instead.
func (*GetDescendantKeysResponse) Descriptor() ([]byte, []int) {
	return file_key_proto_rawDescGZIP(), []int{10}
}

func (x *GetDescendantKeysResponse) GetKeyTree() []*KeyTree {
	if x != nil {
		return x.KeyTree
	}
	return nil
}

var File_key_proto protoreflect.FileDescriptor

const file_key_proto_rawDesc = "" +
	"\n" +
	"\tkey.proto\x12\x10krypton.v1.admin\"\xcc\x03\n" +
	"\x03Key\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"managed_by\x18\x06 \x01(\tR\tmanagedBy\x129\n" +
	"\x06labels\x18\a \x03(\v2!.krypton.v1.admin.Key.LabelsEntryR\x06labels\x12(\n" +
	"\x10life_cycle_state\x18\b \x01(\tR\x0elifeCycleState\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12V\n" +
	"\x14key_processing_state\x18\v \x01(\v2$.krypton.v1.admin.KeyProcessingStateR\x12keyProcessingState\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x12KeyProcessingState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\x9c\x02\n" +
	"\x12AnnounceKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1f\n" +
	"\vtarget_name\x18\x05 \x01(\tR\n" +
	"targetName\x12H\n" +
	"\x06labels\x18\x06 \x03(\v20.krypton.v1.admin.AnnounceKeyRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x13AnnounceKeyResponse\x12'\n" +
	"\x03key\x18\x01 \x01(\v2\x15.krypton.v1.admin.KeyR\x03key\"<\n" +
	"\rGetKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"9\n" +
	"\x0eGetKeyResponse\x12'\n" +
	"\x03key\x18\x01 \x01(\v2\x15.krypton.v1.admin.KeyR\x03key\"C\n" +
	"\x14GetParentKeysRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"B\n" +
	"\x15GetParentKeysResponse\x12)\n" +
	"\x04keys\x18\x01 \x03(\v2\x15.krypton.v1.admin.KeyR\x04keys\"G\n" +
	"\x18GetDescendantKeysRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"4\n" +
	"\aKeyTree\x12)\n" +
	"\x04keys\x18\x01 \x03(\v2\x15.krypton.v1.admin.KeyR\x04keys\"Q\n" +
	"\x19GetDescendantKeysResponse\x124\n" +
	"\bkey_tree\x18\x01 \x03(\v2\x19.krypton.v1.admin.KeyTreeR\akeyTree2\x85\x03\n" +
	"\n" +
	"KeyService\x12Z\n" +
	"\vAnnounceKey\x12$.krypton.v1.admin.AnnounceKeyRequest\x1a%.krypton.v1.admin.AnnounceKeyResponse\x12K\n" +
	"\x06GetKey\x12\x1f.krypton.v1.admin.GetKeyRequest\x1a .krypton.v1.admin.GetKeyResponse\x12`\n" +
	"\rGetParentKeys\x12&.krypton.v1.admin.GetParentKeysRequest\x1a'.krypton.v1.admin.GetParentKeysResponse\x12l\n" +
	"\x11GetDescendantKeys\x12*.krypton.v1.admin.GetDescendantKeysRequest\x1a+.krypton.v1.admin.GetDescendantKeysResponseB3Z1github.com/openkcm/krypton/pkg/api/v1/proto/adminb\x06proto3"

var (
	file_key_proto_rawDescOnce sync.Once
	file_key_proto_rawDescData []byte
)

func file_key_proto_rawDescGZIP() []byte {
	file_key_proto_rawDescOnce.Do(func() {
		file_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)))
	})
	return file_key_proto_rawDescData
}

var file_key_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_key_proto_goTypes = []any{
	(*Key)(nil),                       // 0: krypton.v1.admin.Key
	(*KeyProcessingState)(nil),        // 1: krypton.v1.admin.KeyProcessingState
	(*AnnounceKeyRequest)(nil),        // 2: krypton.v1.admin.AnnounceKeyRequest
	(*AnnounceKeyResponse)(nil),       // 3: krypton.v1.admin.AnnounceKeyResponse
	(*GetKeyRequest)(nil),             // 4: krypton.v1.admin.GetKeyRequest
	(*GetKeyResponse)(nil),            // 5: krypton.v1.admin.GetKeyResponse
	(*GetParentKeysRequest)(nil),      // 6: krypton.v1.admin.GetParentKeysRequest
	(*GetParentKeysResponse)(nil),     // 7: krypton.v1.admin.GetParentKeysResponse
	(*GetDescendantKeysRequest)(nil),  // 8: krypton.v1.admin.GetDescendantKeysRequest
	(*KeyTree)(nil),                   // 9: krypton.v1.admin.KeyTree
	(*GetDescendantKeysResponse)(nil), // 10: krypton.v1.admin.GetDescendantKeysResponse
	nil,                               // 11: krypton.v1.admin.Key.LabelsEntry
	nil,                               // 12: krypton.v1.admin.AnnounceKeyRequest.LabelsEntry
}
var file_key_proto_depIdxs = []int32{
	11, // 0: krypton.v1.admin.Key.labels:type_name -> krypton.v1.admin.Key.LabelsEntry
	1,  // 1: krypton.v1.admin.Key.key_processing_state:type_name -> krypton.v1.admin.KeyProcessingState
	12, // 2: krypton.v1.admin.AnnounceKeyRequest.labels:type_name -> krypton.v1.admin.AnnounceKeyRequest.LabelsEntry
	0,  // 3: krypton.v1.admin.AnnounceKeyResponse.key:type_name -> krypton.v1.admin.Key
	0,  // 4: krypton.v1.admin.GetKeyResponse.key:type_name -> krypton.v1.admin.Key
	0,  // 5: krypton.v1.admin.GetParentKeysResponse.keys:type_name -> krypton.v1.admin.Key
	0,  // 6: krypton.v1.admin.KeyTree.keys:type_name -> krypton.v1.admin.Key
	9,  // 7: krypton.v1.admin.GetDescendantKeysResponse.key_tree:type_name -> krypton.v1.admin.KeyTree
	2,  // 8: krypton.v1.admin.KeyService.AnnounceKey:input_type -> krypton.v1.admin.AnnounceKeyRequest
	4,  // 9: krypton.v1.admin.KeyService.GetKey:input_type -> krypton.v1.admin.GetKeyRequest
	6,  // 10: krypton.v1.admin.KeyService.GetParentKeys:input_type -> krypton.v1.admin.GetParentKeysRequest
	8,  // 11: krypton.v1.admin.KeyService.GetDescendantKeys:input_type -> krypton.v1.admin.GetDescendantKeysRequest
	3,  // 12: krypton.v1.admin.KeyService.AnnounceKey:output_type -> krypton.v1.admin.AnnounceKeyResponse
	5,  // 13: krypton.v1.admin.KeyService.GetKey:output_type -> krypton.v1.admin.GetKeyResponse
	7,  // 14: krypton.v1.admin.KeyService.GetParentKeys:output_type -> krypton.v1.admin.GetParentKeysResponse
	10, // 15: krypton.v1.admin.KeyService.GetDescendantKeys:output_type -> krypton.v1.admin.GetDescendantKeysResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_key_proto_init() }
func file_key_proto_init() {
	if File_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_proto_rawDesc), len(file_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_proto_goTypes,
		DependencyIndexes: file_key_proto_depIdxs,
		MessageInfos:      file_key_proto_msgTypes,
	}.Build()
	File_key_proto = out.File
	file_key_proto_goTypes = nil
	file_key_proto_depIdxs = nil
}
