syntax = "proto3";


package krypton.v1.agents;

option go_package = "github.com/openkcm/krypton/pkg/api/v1/proto/agents";

service Service {
  rpc Register(RegisterAgentRequest) returns (RegisterAgentResponse) {}
  rpc SendHeartbeat(SendHeartbeatRequest) returns (SendHeartbeatResponse) {}
  rpc Deregister(DeregisterAgentRequest) returns (DeregisterAgentResponse) {}
}

message RegisterAgentRequest {
  string agent_name = 1;
  string instance_id = 2;
}

message RegisterAgentResponse {
  bytes config = 1;
}

message SendHeartbeatRequest {
  string agent_name = 1;
  string instance_id = 2;
}

message SendHeartbeatResponse {
}

message DeregisterAgentRequest {
  string agent_name = 1;
  string instance_id = 2;
}

message DeregisterAgentResponse {
}
