// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sealer.proto

package sealer

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyVersion    int32                  `protobuf:"varint,3,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,4,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Aad           []byte                 `protobuf:"bytes,5,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealRequest) Reset() {
	*x = SealRequest{}
	mi := &file_sealer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealRequest) ProtoMessage() {}

func (x *SealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sealer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealRequest.ProtoReflect.Descriptor instead.
func (*SealRequest) Descriptor() ([]byte, []int) {
	return file_sealer_proto_rawDescGZIP(), []int{0}
}

func (x *SealRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SealRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SealRequest) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *SealRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *SealRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

type SealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealResponse) Reset() {
	*x = SealResponse{}
	mi := &file_sealer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealResponse) ProtoMessage() {}

func (x *SealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sealer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealResponse.ProtoReflect.Descriptor instead.
func (*SealResponse) Descriptor() ([]byte, []int) {
	return file_sealer_proto_rawDescGZIP(), []int{1}
}

func (x *SealResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type UnsealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyVersion    int32                  `protobuf:"varint,3,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Aad           []byte                 `protobuf:"bytes,5,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealRequest) Reset() {
	*x = UnsealRequest{}
	mi := &file_sealer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealRequest) ProtoMessage() {}

func (x *UnsealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sealer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealRequest.ProtoReflect.Descriptor instead.
func (*UnsealRequest) Descriptor() ([]byte, []int) {
	return file_sealer_proto_rawDescGZIP(), []int{2}
}

func (x *UnsealRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UnsealRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UnsealRequest) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *UnsealRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *UnsealRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

type UnsealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealResponse) Reset() {
	*x = UnsealResponse{}
	mi := &file_sealer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealResponse) ProtoMessage() {}

func (x *UnsealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sealer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealResponse.ProtoReflect.Descriptor instead.
func (*UnsealResponse) Descriptor() ([]byte, []int) {
	return file_sealer_proto_rawDescGZIP(), []int{3}
}

func (x *UnsealResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

var File_sealer_proto protoreflect.FileDescriptor

const file_sealer_proto_rawDesc = "" +
	"\n" +
	"\fsealer.proto\x12\x11krypton.v1.sealer\"\x92\x01\n" +
	"\vSealRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vkey_version\x18\x03 \x01(\x05R\n" +
	"keyVersion\x12\x1c\n" +
	"\tplaintext\x18\x04 \x01(\fR\tplaintext\x12\x10\n" +
	"\x03aad\x18\x05 \x01(\fR\x03aad\".\n" +
	"\fSealResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\"\x96\x01\n" +
	"\rUnsealRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vkey_version\x18\x03 \x01(\x05R\n" +
	"keyVersion\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x10\n" +
	"\x03aad\x18\x05 \x01(\fR\x03aad\".\n" +
	"\x0eUnsealResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext2\xa1\x01\n" +
	"\aService\x12G\n" +
	"\x04Seal\x12\x1e.krypton.v1.sealer.SealRequest\x1a\x1f.krypton.v1.sealer.SealResponse\x12M\n" +
	"\x06Unseal\x12 .krypton.v1.sealer.UnsealRequest\x1a!.krypton.v1.sealer.UnsealResponseB4Z2github.com/openkcm/krypton/pkg/api/v1/proto/sealerb\x06proto3"

var (
	file_sealer_proto_rawDescOnce sync.Once
	file_sealer_proto_rawDescData []byte
)

func file_sealer_proto_rawDescGZIP() []byte {
	file_sealer_proto_rawDescOnce.Do(func() {
		file_sealer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sealer_proto_rawDesc), len(file_sealer_proto_rawDesc)))
	})
	return file_sealer_proto_rawDescData
}

var file_sealer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sealer_proto_goTypes = []any{
	(*SealRequest)(nil),    // 0: krypton.v1.sealer.SealRequest
	(*SealResponse)(nil),   // 1: krypton.v1.sealer.SealResponse
	(*UnsealRequest)(nil),  // 2: krypton.v1.sealer.UnsealRequest
	(*UnsealResponse)(nil), // 3: krypton.v1.sealer.UnsealResponse
}
var file_sealer_proto_depIdxs = []int32{
	0, // 0: krypton.v1.sealer.Service.Seal:input_type -> krypton.v1.sealer.SealRequest
	2, // 1: krypton.v1.sealer.Service.Unseal:input_type -> krypton.v1.sealer.UnsealRequest
	1, // 2: krypton.v1.sealer.Service.Seal:output_type -> krypton.v1.sealer.SealResponse
	3, // 3: krypton.v1.sealer.Service.Unseal:output_type -> krypton.v1.sealer.UnsealResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sealer_proto_init() }
func file_sealer_proto_init() {
	if File_sealer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sealer_proto_rawDesc), len(file_sealer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sealer_proto_goTypes,
		DependencyIndexes: file_sealer_proto_depIdxs,
		MessageInfos:      file_sealer_proto_msgTypes,
	}.Build()
	File_sealer_proto = out.File
	file_sealer_proto_goTypes = nil
	file_sealer_proto_depIdxs = nil
}
