syntax = "proto3";


package krypton.v1.admin.jobs;

option go_package = "github.com/openkcm/krypton/pkg/api/v1/proto/admin/jobs";

service JobService {
  rpc GetJobGroup(GetJobGroupRequest) returns (GetJobGroupResponse);
}

message Job {
  string id = 1;
  string type = 2;
  string status = 3;
  string error_message = 4;
}

message JobGroup {
  string id = 1;
  string type = 2;
  string status = 3;
  string error_message = 4;
  repeated Job jobs = 5;
}

message GetJobGroupRequest {
  string id = 1;
}

message GetJobGroupResponse {
  JobGroup job_group = 1;
}
