apiVersion: v1
kind: Service
metadata:
  name: krypton-root-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: krypton-root-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krypton-root-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krypton-root-postgres
  template:
    metadata:
      labels:
        app: krypton-root-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: krypton
            - name: POSTGRES_PASSWORD
              value: krypton
            - name: POSTGRES_DB
              value: krypton
