name: root
role: root
segment:
  start_kind: K0
  end_kind: K1
selector_labels:
  environment: production
key_bindings:
  K0:
    cryptor:
      name: root-cryptor
      type: hsm
  K1:
    vault:
      name: root-vault
      type: unsafe-sqlite-memory
    cryptor:
      name: root-cryptor
      type: aes256gcm
    parent_key_provider:
      agent_name: root
hierarchy:
  name: production-hierarchy
  key_specs:
    - kind: K0
      role: root
      algorithm: AES256
      labels_spec:
        allow_user_labels: true
    - kind: K1
      role: kek
      algorithm: AES256
      labels_spec:
        allow_user_labels: true
    - kind: K2
      role: tek
      algorithm: AES256
      labels_spec:
        allow_user_labels: true
    - kind: K3
      role: dek
      algorithm: AES256
      labels_spec:
        allow_user_labels: true
topology:
  segments:
    - name: agent-k1
      segment:
        start_kind: K2
        end_kind: K3
      key_bindings:
        K2:
          vault:
            name: agent-vault
            type: unsafe-sqlite-memory
          cryptor:
            name: agent-cryptor
            type: aes256gcm
          parent_key_provider:
            agent_name: root
        K3:
          vault:
            name: agent-dek-vault
            type: unsafe-sqlite
            config:
              path: agent-dek
          cryptor:
            name: agent-cryptor
            type: hsm # aka static secret cryptor as for now
      selector_labels:
        cloud: aws
reconciler:
  targets:
    - name: agent-k1
      address: localhost:9091
