// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: actions.proto

package actions

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ANNOUNCE_KEY            ActionType = 1
	ActionType_ACTIVATE_KEY            ActionType = 2
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ANNOUNCE_KEY",
		2: "ACTIVATE_KEY",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ANNOUNCE_KEY":            1,
		"ACTIVATE_KEY":            2,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_actions_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_actions_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{0}
}

type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_TARGET_TYPE_TENANT      TargetType = 1
	TargetType_TARGET_TYPE_KEY         TargetType = 2
	TargetType_TARGET_TYPE_KEY_VERSION TargetType = 3
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_TYPE_TENANT",
		2: "TARGET_TYPE_KEY",
		3: "TARGET_TYPE_KEY_VERSION",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_TYPE_TENANT":      1,
		"TARGET_TYPE_KEY":         2,
		"TARGET_TYPE_KEY_VERSION": 3,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_actions_proto_enumTypes[1].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_actions_proto_enumTypes[1]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{1}
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ActionType             `protobuf:"varint,2,opt,name=type,proto3,enum=krypton.v1.admin.actions.ActionType" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TargetType    TargetType             `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3,enum=krypton.v1.admin.actions.TargetType" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Cascading     bool                   `protobuf:"varint,6,opt,name=cascading,proto3" json:"cascading,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *Action) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Action) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *Action) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Action) GetCascading() bool {
	if x != nil {
		return x.Cascading
	}
	return false
}

func (x *Action) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Action) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionRequest) Reset() {
	*x = GetActionRequest{}
	mi := &file_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionRequest) ProtoMessage() {}

func (x *GetActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionRequest.ProtoReflect.Descriptor instead.
func (*GetActionRequest) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{1}
}

func (x *GetActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *Action                `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionResponse) Reset() {
	*x = GetActionResponse{}
	mi := &file_actions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionResponse) ProtoMessage() {}

func (x *GetActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionResponse.ProtoReflect.Descriptor instead.
func (*GetActionResponse) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{2}
}

func (x *GetActionResponse) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_actions_proto protoreflect.FileDescriptor

const file_actions_proto_rawDesc = "" +
	"\n" +
	"\ractions.proto\x12\x18krypton.v1.admin.actions\"\xaa\x02\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.krypton.v1.admin.actions.ActionTypeR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12E\n" +
	"\vtarget_type\x18\x04 \x01(\x0e2$.krypton.v1.admin.actions.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12\x1c\n" +
	"\tcascading\x18\x06 \x01(\bR\tcascading\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\"\n" +
	"\x10GetActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x11GetActionResponse\x128\n" +
	"\x06action\x18\x01 \x01(\v2 .krypton.v1.admin.actions.ActionR\x06action*M\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fANNOUNCE_KEY\x10\x01\x12\x10\n" +
	"\fACTIVATE_KEY\x10\x02*s\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TARGET_TYPE_TENANT\x10\x01\x12\x13\n" +
	"\x0fTARGET_TYPE_KEY\x10\x02\x12\x1b\n" +
	"\x17TARGET_TYPE_KEY_VERSION\x10\x032u\n" +
	"\rActionService\x12d\n" +
	"\tGetAction\x12*.krypton.v1.admin.actions.GetActionRequest\x1a+.krypton.v1.admin.actions.GetActionResponseB;Z9github.com/openkcm/krypton/pkg/api/v1/proto/admin/actionsb\x06proto3"

var (
	file_actions_proto_rawDescOnce sync.Once
	file_actions_proto_rawDescData []byte
)

func file_actions_proto_rawDescGZIP() []byte {
	file_actions_proto_rawDescOnce.Do(func() {
		file_actions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actions_proto_rawDesc), len(file_actions_proto_rawDesc)))
	})
	return file_actions_proto_rawDescData
}

var file_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_actions_proto_goTypes = []any{
	(ActionType)(0),           // 0: krypton.v1.admin.actions.ActionType
	(TargetType)(0),           // 1: krypton.v1.admin.actions.TargetType
	(*Action)(nil),            // 2: krypton.v1.admin.actions.Action
	(*GetActionRequest)(nil),  // 3: krypton.v1.admin.actions.GetActionRequest
	(*GetActionResponse)(nil), // 4: krypton.v1.admin.actions.GetActionResponse
}
var file_actions_proto_depIdxs = []int32{
	0, // 0: krypton.v1.admin.actions.Action.type:type_name -> krypton.v1.admin.actions.ActionType
	1, // 1: krypton.v1.admin.actions.Action.target_type:type_name -> krypton.v1.admin.actions.TargetType
	2, // 2: krypton.v1.admin.actions.GetActionResponse.action:type_name -> krypton.v1.admin.actions.Action
	3, // 3: krypton.v1.admin.actions.ActionService.GetAction:input_type -> krypton.v1.admin.actions.GetActionRequest
	4, // 4: krypton.v1.admin.actions.ActionService.GetAction:output_type -> krypton.v1.admin.actions.GetActionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_actions_proto_init() }
func file_actions_proto_init() {
	if File_actions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actions_proto_rawDesc), len(file_actions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_actions_proto_goTypes,
		DependencyIndexes: file_actions_proto_depIdxs,
		EnumInfos:         file_actions_proto_enumTypes,
		MessageInfos:      file_actions_proto_msgTypes,
	}.Build()
	File_actions_proto = out.File
	file_actions_proto_goTypes = nil
	file_actions_proto_depIdxs = nil
}
