#!/bin/bash
set -euo pipefail

# Usage: ./generate-client-certs.sh <tenantID> [certs_dir]
# Example: ./generate-client-certs.sh "1ff6e7cd-8581-431f-9103-56fe8620049f" ./certs
#
# Requires CA cert and key to already exist in certs_dir (generated by generate-server-certs.sh).
# Generates a client certificate signed by the CA with tenantID as the CN,
# and bundles the client cert + key into a single PEM file.

TENANT_ID="${1:?Usage: $0 <tenantID> [certs_dir]}"
CERTS_DIR="${2:-./certs}"
DAYS_VALID=365

# Validate that CA files exist
if [[ ! -f "$CERTS_DIR/ca.pem" ]] || [[ ! -f "$CERTS_DIR/ca-key.pem" ]]; then
  echo "Error: CA files not found in $CERTS_DIR"
  echo "Run generate-server-certs.sh first to create the CA."
  exit 1
fi

echo "Generating client certificate for tenant: $TENANT_ID"
echo "Using CA from: $CERTS_DIR"

# --- Client Certificate (tenantID as CN) ---
echo "[1/1] Generating client certificate with tenantID as CN..."
openssl req -newkey rsa:4096 -nodes \
  -keyout "$CERTS_DIR/client-key.pem" \
  -out "$CERTS_DIR/client.csr" \
  -subj "/CN=$TENANT_ID" \
  2>/dev/null

openssl x509 -req \
  -in "$CERTS_DIR/client.csr" \
  -CA "$CERTS_DIR/ca.pem" \
  -CAkey "$CERTS_DIR/ca-key.pem" \
  -CAcreateserial \
  -out "$CERTS_DIR/client-cert.pem" \
  -days "$DAYS_VALID" \
  2>/dev/null

# Bundle client cert + key into single PEM
cat "$CERTS_DIR/client-cert.pem" "$CERTS_DIR/client-key.pem" > "$CERTS_DIR/client.pem"

# --- Cleanup temp files ---
rm -f "$CERTS_DIR"/*.csr "$CERTS_DIR"/*.srl "$CERTS_DIR"/client-cert.pem "$CERTS_DIR"/client-key.pem

echo ""
echo "Done! Generated client bundle:"
echo "  Client cert+key: $CERTS_DIR/client.pem (CN=$TENANT_ID)"
