net:
   bindIp: 0.0.0.0

security:
   enableEncryption: true
   kmip:
      serverName: "krypton"
      port: 5696
      serverCAFile: "/etc/tls/cert/ca.pem"
      clientCertificateFile: "/etc/tls/cert/client.pem"
      useLegacyProtocol: false
      # KMIP server must have this key pre-seeded (tenantID:keyID:Version)
      keyIdentifier: "b5731544-fcfe-4bf4-abca-4dc6ee7d8f90:ae53acb6-1d8b-49c7-94c2-7d25045e2237:2"
