// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: tenants.proto

package tenants

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTenantRequest) Reset() {
	*x = UpsertTenantRequest{}
	mi := &file_tenants_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantRequest) ProtoMessage() {}

func (x *UpsertTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantRequest.ProtoReflect.Descriptor instead.
func (*UpsertTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenants_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertTenantRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpsertTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTenantResponse) Reset() {
	*x = UpsertTenantResponse{}
	mi := &file_tenants_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantResponse) ProtoMessage() {}

func (x *UpsertTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenants_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantResponse.ProtoReflect.Descriptor instead.
func (*UpsertTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenants_proto_rawDescGZIP(), []int{1}
}

var File_tenants_proto protoreflect.FileDescriptor

const file_tenants_proto_rawDesc = "" +
	"\n" +
	"\rtenants.proto\x12\x19krypton.v1.agents.tenants\"\xc8\x01\n" +
	"\x13UpsertTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12R\n" +
	"\x06labels\x18\x03 \x03(\v2:.krypton.v1.agents.tenants.UpsertTenantRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14UpsertTenantResponse2\x82\x01\n" +
	"\rTenantService\x12q\n" +
	"\fUpsertTenant\x12..krypton.v1.agents.tenants.UpsertTenantRequest\x1a/.krypton.v1.agents.tenants.UpsertTenantResponse\"\x00B<Z:github.com/openkcm/krypton/pkg/api/v1/proto/agents/tenantsb\x06proto3"

var (
	file_tenants_proto_rawDescOnce sync.Once
	file_tenants_proto_rawDescData []byte
)

func file_tenants_proto_rawDescGZIP() []byte {
	file_tenants_proto_rawDescOnce.Do(func() {
		file_tenants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenants_proto_rawDesc), len(file_tenants_proto_rawDesc)))
	})
	return file_tenants_proto_rawDescData
}

var file_tenants_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tenants_proto_goTypes = []any{
	(*UpsertTenantRequest)(nil),  // 0: krypton.v1.agents.tenants.UpsertTenantRequest
	(*UpsertTenantResponse)(nil), // 1: krypton.v1.agents.tenants.UpsertTenantResponse
	nil,                          // 2: krypton.v1.agents.tenants.UpsertTenantRequest.LabelsEntry
}
var file_tenants_proto_depIdxs = []int32{
	2, // 0: krypton.v1.agents.tenants.UpsertTenantRequest.labels:type_name -> krypton.v1.agents.tenants.UpsertTenantRequest.LabelsEntry
	0, // 1: krypton.v1.agents.tenants.TenantService.UpsertTenant:input_type -> krypton.v1.agents.tenants.UpsertTenantRequest
	1, // 2: krypton.v1.agents.tenants.TenantService.UpsertTenant:output_type -> krypton.v1.agents.tenants.UpsertTenantResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tenants_proto_init() }
func file_tenants_proto_init() {
	if File_tenants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenants_proto_rawDesc), len(file_tenants_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenants_proto_goTypes,
		DependencyIndexes: file_tenants_proto_depIdxs,
		MessageInfos:      file_tenants_proto_msgTypes,
	}.Build()
	File_tenants_proto = out.File
	file_tenants_proto_goTypes = nil
	file_tenants_proto_depIdxs = nil
}
